spring:
  application:
    name: profile-service
  data:
    mongodb:
      uri: mongodb+srv://root:root@cluster0.ap9dw.mongodb.net/test
      database: shoppingcart
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    path: /profile-service-swagger.html
  operationsSorter: method
jwtSecret: secret
jwtExpiration: 86400